### ISSUE TITLE
Pod unable to start, healthz endpoint failure

### ISSUE THREAD

**Issue by diegodambra** [slicen/cert-manager-webhook-linode#8]
Pod never enters ready state. Log output:
`E1108 11:03:58.888092       1 cmd.go:46] cert-manager "msg"="error executing command" "error"="unknown flag: --v"`

Issue can be fixed by setting values to:
```yaml
    values:
      - deployment:
          logLevel: null
```
Seems like `--v` is a no longer supported argument.

Note docker image `slicen/cert-manager-webhook-linode:v0.1.0` does work.
